"""Exact-replay tests (DESIGN.md §6): seeded runs driven through the real
input dispatch. The solution strings are pinned to the current balance
constants — when tuning changes them, regenerate with find_solution.py.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import game as d


def play(seed, keys):
    run = d.Run(seed=seed)
    for k in keys:
        run = d.dispatch(run, k)
        if run.over:
            break
    return run


def snapshot(run):
    return (run.ring, run.player, tuple(sorted(run.hunters)),
            tuple(sorted(run.killers)), tuple(sorted(run.junk)),
            run.trace, run.turn, run.carried, run.creds_taken,
            run.over, run.won)


def test_same_seed_same_keys_same_run():
    # aimless script that exercises the rng (panic twice) and scanning
    script = "hh..jjp..kkll..p.snnn....bb"
    a, b = d.Run(seed=77), d.Run(seed=77)
    assert snapshot(a) == snapshot(b)
    for k in script:
        a, b = d.dispatch(a, k), d.dispatch(b, k)
        assert snapshot(a) == snapshot(b)
        if a.over:
            break


def test_shallow_solution_replays_exactly():
    # generated by find_solution.py: walk to the ring-1 port, jack out
    run = play(9, "ulnnnlljybbbnllnululnn<")
    assert run.won and run.ring == 1
    assert "ring 1 port" in run.over
    assert (run.trace, run.turn, run.carried) == (22, 22, 0)


def test_deep_solution_replays_exactly():
    # generated by find_solution.py --deep: descend to ring 0, jack out;
    # crossing the port swaps the Run, so this covers the whole descent
    run = play(223, "uluuuuuuuulllllln>uuuuuulllllll<")
    assert run.won and run.ring == 0
    assert "ring 0 port" in run.over
    assert (run.trace, run.turn, run.carried) == (30, 13, 0)


if __name__ == "__main__":
    checks = [v for k, v in sorted(globals().items())
              if k.startswith("test_")]
    for check in checks:
        check()
        print(f"ok  {check.__name__}")
    print(f"ALL {len(checks)} CHECKS PASSED")
